-   name: run update dynamodb to ondemand
    tags: always
    debug:
        msg: "region: {{ params.0 }}"

-   set_fact:
        region: "{{ params.0 }}"

-   name: dynamodb list-tables
    command: aws --region {{ region }} dynamodb list-tables
    register: result_list_tables

-   set_fact:
        items: "{{ (result_list_tables.stdout | from_json).TableNames }}"

-   name: debug all items in {{ region }}
    tags: debug, never
    debug: var=items

-   name: update table to ondemand
    command: aws --region {{ region }} dynamodb update-table --table-name {{ item }} --billing-mode PAY_PER_REQUEST
    loop: "{{ items }}"
