    -   name: print aws credentials
        tags: always
        debug:
            msg:
                AWS_ACCESS_KEY_ID: "{{lookup('env', 'AWS_ACCESS_KEY_ID')}}"
                AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') | regex_replace('^[\\d\\w\\/+]{32}', '********') }}"
    -   name: check AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables
        tags: always
        fail:
            msg: >
                AWS credentiala check failed. AWS_ACCESS_KEY_ID and/or AWS_SECRET_ACCESS_KEY not found.
                Use export AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY to set environment variables.
        when:
            lookup('env', 'AWS_ACCESS_KEY_ID') | length <= 0 or lookup('env', 'AWS_SECRET_ACCESS_KEY') | length <= 0

    -   name: run aws_caller_info
        tags: always
        register: aws_caller_info
        aws_caller_info:

    -   name: gather aws facts
        tags: always
        set_fact:
            aws_facts:
                iam:
                    accountId: "{{ aws_caller_info.account }}"
                    accountAlias: "{{ aws_caller_info.account_alias }}"
                    arn: "{{ aws_caller_info.arn }}"
                    userId: "{{ aws_caller_info.user_id }}"

    -   name: print variables
        tags: debug, never
        debug:
            msg:
                hostvars: "{{ hostvars }}"
